### ISSUE TITLE
翻訳: Introduction to Plugin Development

### ISSUE THREAD

**Issue by ghost** [jawordpressorg/plugin-handbook#3]
以下のページの翻訳をします。

**翻訳するページのURL**

https://developer.wordpress.org/plugins/intro/

**翻訳するページのリポジトリ内のパス**

https://github.com/jawordpressorg/plugin-handbook/blob/main/plugins/intro.md

**原文との差分チェック**

- [x] 原文ページとリポジトリ内の内容が同じものか確認済み

**Comment by t-hamano** [comment]
こちらのページは既に日本語化が完了していると思いますので、クローズします。
