### ISSUE TITLE
翻訳: /plugins/intro/what-is-a-plugin/

### ISSUE THREAD

**Issue by ghost** [jawordpressorg/plugin-handbook#5]
以下のページの翻訳をします。

**翻訳するページのURL**

https://developer.wordpress.org/plugins/intro/what-is-a-plugin/

**翻訳するページのリポジトリ内のパス**

/plugins/intro/

**原文との差分チェック**

- [x] 原文ページとリポジトリ内の内容が同じものか確認済み（ざっくりで良いです）

**Comment by t-hamano** [comment]
こちらのページは既に日本語化が完了していると思いますので、クローズします。
